version: "3.8"
services:
  mysql-db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app_calculo_sueldos
    ports:
      - 33080:3308
  app_sueldos:
    container_name:  calculo-sueldos
    image: gigavice/calculo-sueldos-app
    ports:
      -  "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3308/app_calculo_sueldos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
