version: "3.8"
services:
  mysql-db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
    ports:
      - 33000:3306
  calculo-sueldos:
    container_name:  calculo-sueldos
    image: gigavice/calculo-sueldos
    ports:
      -  "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
